name: ali_fouad_test
description: "A Flutter Test project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  #animate aplash screen
  animated_splash_screen: ^1.3.0

  #check device connectivity
  connectivity: null
  
  #country_code_picker
  country_code_picker: ^3.0.0
  
  cupertino_icons: ^1.0.2

  #network manager
  dio: ^5.4.1
  flutter:
    sdk: flutter

  #change app launcger icon
  flutter_launcher_icons: ^0.13.1
  
  #loading indicators
  flutter_spinkit: ^5.2.0

  #add a Padding around these widgets but it's very verbose
  gap: ^3.0.1

  #GetX Framework
  get: ^4.6.6

  #caching storage
  get_storage: ^2.1.1

  #network manager
  http: ^1.1.0

  #A Flutter package for easy text formatting with customizable styles between specified marks.
  special_text_between_marks: ^0.0.2

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AlexandriaFLF
      fonts:
        - asset: assets/fonts/AlexandriaFLF.ttf
    - family: AlexandriaFLF-Bold
      fonts:
        - asset: assets/fonts/AlexandriaFLF-Bold.ttf
    - family: AlexandriaFLF-Italic
      fonts:
        - asset: assets/fonts/AlexandriaFLF-Italic.ttf
          style: italic
